# build stage
FROM node:12.18.4-alpine as builder
WORKDIR /build

COPY ./package* ./
RUN npm ci

COPY . .
RUN npm run generate

# production stage
FROM nginx:stable-alpine as production-stage
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /build/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]