export const state = () => ({
  customerQueue: [
    {
      id: 1,
      name: 'นายเอ สามสกุลบี',
      address: '55/55 ต.รัษฎา อ.เมือง จ.ภูเก็ต',
      email: 'myemailaddress@gmail.com',
      tel: '098-765-4321',
      other: 'ไม่มี',
      status: {
        doctor: 'สพญ.เอบีซี ดีอีเอฟ',
        important: 'ธรรมดา',
        problem: '',
        status: 'รอตรวจ',
        temp: '50',
        time: '2020-08-31, 11:25:09 am',
        type: 'OPD',
        weight: '50',
        do: {
          check: [],
          other: '',
        },
      },
      pet: {
        name: 'Snow',
        status: 'ทั่วไป',
        microship: '',
        bd: '2014-11-05',
        type: 'หมา',
        specie: 'บางแก้ว',
        gender: 'เมีย',
        color: 'ขาวน้ำตาล',
        sterile: 'ทำแล้ว',
        scar: '-',
        appoint: '10/08/2020',
      },
    },
    {
      id: 2,
      name: 'นายเอ สามสกุลบี',
      address: '55/55 ต.รัษฎา อ.เมือง จ.ภูเก็ต',
      email: 'myemailaddress@gmail.com',
      tel: '098-765-4321',
      other: 'ไม่มี',
      status: {
        doctor: 'สพญ.เอบีซี ดีอีเอฟ',
        important: 'ธรรมดา',
        problem: '',
        status: 'รอชำระเงิน',
        temp: '50',
        time: '2020-08-30, 11:25:09 am',
        type: 'OPD',
        weight: '50',
        do: {
          check: [],
          other: '',
        },
      },
      pet: {
        name: 'Snow',
        status: 'ทั่วไป',
        microship: '',
        bd: '2014-11-05',
        type: 'หมา',
        specie: 'บางแก้ว',
        gender: 'เมีย',
        color: 'ขาวน้ำตาล',
        sterile: 'ทำแล้ว',
        scar: '-',
        appoint: '10/08/2020',
      },
    },
    {
      id: 3,
      name: 'นายเอ สามสกุลบี',
      address: '55/55 ต.รัษฎา อ.เมือง จ.ภูเก็ต',
      email: 'myemailaddress@gmail.com',
      tel: '098-765-4321',
      other: 'ไม่มี',
      status: {
        doctor: 'สพญ.เอบีซี ดีอีเอฟ',
        important: 'ธรรมดา',
        problem: '',
        status: 'กำลังตรวจ',
        temp: '50',
        time: '2020-08-31, 01:25:09 am',
        type: 'OPD',
        weight: '50',
        do: {
          check: [],
          other: '',
        },
      },
      pet: {
        name: 'Snow',
        status: 'ทั่วไป',
        microship: '',
        bd: '2014-11-05',
        type: 'หมา',
        specie: 'บางแก้ว',
        gender: 'เมีย',
        color: 'ขาวน้ำตาล',
        sterile: 'ทำแล้ว',
        scar: '-',
        appoint: '10/08/2020',
      },
    },
    {
      id: 4,
      name: 'นายเอ สามสกุลบี',
      address: '55/55 ต.รัษฎา อ.เมือง จ.ภูเก็ต',
      email: 'myemailaddress@gmail.com',
      tel: '098-765-4321',
      other: 'ไม่มี',
      status: {
        doctor: 'สพญ.เอบีซี ดีอีเอฟ',
        important: 'ธรรมดา',
        problem: '',
        status: 'รอผลตรวจ',
        temp: '50',
        time: '2020-08-31, 11:25:09 am',
        type: 'OPD',
        weight: '50',
        do: {
          check: [],
          other: '',
        },
      },
      pet: {
        name: 'Snow',
        status: 'ทั่วไป',
        microship: '',
        bd: '2014-11-05',
        type: 'หมา',
        specie: 'บางแก้ว',
        gender: 'เมีย',
        color: 'ขาวน้ำตาล',
        sterile: 'ทำแล้ว',
        scar: '-',
        appoint: '10/08/2020',
      },
    },
    {
      id: 1,
      name: 'นายเอ สามสกุลบี',
      address: '55/55 ต.รัษฎา อ.เมือง จ.ภูเก็ต',
      email: 'myemailaddress@gmail.com',
      tel: '098-765-4321',
      other: 'ไม่มี',
      status: {
        doctor: 'สพญ.เอบีซี ดีอีเอฟ',
        important: 'ธรรมดา',
        problem: '',
        status: 'Admit',
        temp: '50',
        time: '2020-08-31, 11:25:09 am',
        type: 'IPD',
        weight: '50',
        do: {
          check: [],
          other: '',
        },
      },
      pet: {
        name: 'Snow',
        status: 'ทั่วไป',
        microship: '',
        bd: '2014-11-05',
        type: 'หมา',
        specie: 'บางแก้ว',
        gender: 'เมีย',
        color: 'ขาวน้ำตาล',
        sterile: 'ทำแล้ว',
        scar: '-',
        appoint: '10/08/2020',
      },
    },
    {
      id: 2,
      name: 'นายเอ สามสกุลบี',
      address: '55/55 ต.รัษฎา อ.เมือง จ.ภูเก็ต',
      email: 'myemailaddress@gmail.com',
      tel: '098-765-4321',
      other: 'ไม่มี',
      status: {
        doctor: 'สพญ.เอบีซี ดีอีเอฟ',
        important: 'ธรรมดา',
        problem: '',
        status: 'รอชำระเงิน',
        temp: '50',
        time: '2020-08-31, 11:25:09 am',
        type: 'IPD',
        weight: '50',
        do: {
          check: [],
          other: '',
        },
      },
      pet: {
        name: 'Snow',
        status: 'ทั่วไป',
        microship: '',
        bd: '2014-11-05',
        type: 'หมา',
        specie: 'บางแก้ว',
        gender: 'เมีย',
        color: 'ขาวน้ำตาล',
        sterile: 'ทำแล้ว',
        scar: '-',
        appoint: '10/08/2020',
      },
    },
    {
      id: 1,
      name: 'นายเอ สามสกุลบี',
      address: '55/55 ต.รัษฎา อ.เมือง จ.ภูเก็ต',
      email: 'myemailaddress@gmail.com',
      tel: '098-765-4321',
      other: 'ไม่มี',
      status: {
        doctor: 'สพญ.เอบีซี ดีอีเอฟ',
        important: 'ธรรมดา',
        problem: '',
        status: 'ฝากเลี้ยง',
        temp: '50',
        time: '2020-08-30, 11:25:09 am',
        type: 'ฝากเลี้ยง',
        weight: '50',
        do: {
          check: [],
          other: '',
        },
      },
      pet: {
        name: 'Snow',
        status: 'ทั่วไป',
        microship: '',
        bd: '2014-11-05',
        type: 'หมา',
        specie: 'บางแก้ว',
        gender: 'เมีย',
        color: 'ขาวน้ำตาล',
        sterile: 'ทำแล้ว',
        scar: '-',
        appoint: '10/08/2020',
      },
    },
    {
      id: 2,
      name: 'นายเอ สามสกุลบี',
      address: '55/55 ต.รัษฎา อ.เมือง จ.ภูเก็ต',
      email: 'myemailaddress@gmail.com',
      tel: '098-765-4321',
      other: 'ไม่มี',
      status: {
        doctor: 'สพญ.เอบีซี ดีอีเอฟ',
        important: 'ธรรมดา',
        problem: '',
        status: 'รอชำระเงิน',
        temp: '50',
        time: '2020-08-31, 11:25:09 am',
        type: 'ฝากเลี้ยง',
        weight: '50',
        do: {
          check: [],
          other: '',
        },
      },
      pet: {
        name: 'Snow',
        status: 'ทั่วไป',
        microship: '',
        bd: '2014-11-05',
        type: 'หมา',
        specie: 'บางแก้ว',
        gender: 'เมีย',
        color: 'ขาวน้ำตาล',
        sterile: 'ทำแล้ว',
        scar: '-',
        appoint: '10/08/2020',
      },
    },
  ],
})

export const mutations = {
  addQueueState(state, queue) {
    state.customerQueue.push(queue)
    // console.log(queue)
  },
}

export const actions = {
  addQueueOPD(vuexContext, customer) {
    const customerQueue = { ...customer.user }
    const petId = customer.petId
    const status = customer.status

    // customerQueue.pet = null

    for (const pet in customerQueue.pet) {
      if (customerQueue.pet[pet].id === petId) {
        const onePet = customerQueue.pet[pet]
        customerQueue.pet = onePet
        break
      }
    }
    customerQueue.status = status
    vuexContext.commit('addQueueState', customerQueue)
    // state.customerQueue.push(customerQueue)
  },
}
