name: ci

on:
  push:
    branches: master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ secrets.CR_USERNAME }} --password-stdin
      - name: Build
        run: docker build -t ghcr.io/${{ secrets.CR_USERNAME }}/vet-clinic-web-spa:latest -f Dockerfile-spa .
      - name: Push
        run: docker image push ghcr.io/${{ secrets.CR_USERNAME }}/vet-clinic-web-spa:latest

  # cd:
  #   runs-on: ubuntu-latest
  #   needs: ci
  #   steps:
  #     - name: executing remote ssh commands
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.DEV_SERVER_HOST }}
  #         username: ${{ secrets.DEV_SERVER_USERNAME }}
  #         key: ${{ secrets.DEV_SERVER_KEY }}
  #         port: ${{ secrets.DEV_SERVER_PORT }}
  #         script: |
  #           cd vc-app
  #           docker-compose pull
  #           docker-compose up -d vc-web
